title: 'Spline_test'
save_path: './saved/'
xlim: [-1, 7]
ylim: [-1, 7]
start_point_pos: [0, 0]
final_point_pos: [5, 0]
speed_accel_parameter: 0.2
speed_decay_parameter: 0.8
total_time_length: 5
num_timesteps: 500
num_delta_t: 500_000
s: 0