title: 'Spline_test'
save_path: './saved/'
xlim: [-1, 6]
ylim: [-1, 6]
start_point_pos: [0, 0]
final_point_pos: [5, 0]
via_speed: [1.0, 2.0, 3.0, 3.0, 3.0]
total_time_length: 5
speed_accel_parameter: 0.2
speed_decay_parameter: 0.8
num_timesteps: 200
num_delta_t: 200_000
s: 0