title: 'Spline_test'
save_path: './saved/'
xlim: [-1, 6]
ylim: [-1, 6]
start_point_pos: [3, 0]
final_point_pos: [3, 0]
speed_accel_parameter: 0
speed_decay_parameter: 1
total_time_length: 5
num_timesteps: 200
num_delta_t: 200_000
s: 0